// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2QHOuHc8sKoyt6L6rfv308WbsRD3cRjY',
    appId: '1:519206703183:web:b3fb3d9fd523ec16b51a3a',
    messagingSenderId: '519206703183',
    projectId: 'portifolio-d00ca',
    authDomain: 'portifolio-d00ca.firebaseapp.com',
    storageBucket: 'portifolio-d00ca.appspot.com',
    measurementId: 'G-V0R74R4GBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmjaShewpwJhatvWdH0rjg2pUklJu3MCo',
    appId: '1:519206703183:android:9ddf79b017496524b51a3a',
    messagingSenderId: '519206703183',
    projectId: 'portifolio-d00ca',
    storageBucket: 'portifolio-d00ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV2i-LxlNgpMV7AYVfiE012AtTEGGX9Gk',
    appId: '1:519206703183:ios:68a805b75f84a439b51a3a',
    messagingSenderId: '519206703183',
    projectId: 'portifolio-d00ca',
    storageBucket: 'portifolio-d00ca.appspot.com',
    iosBundleId: 'com.example.portifolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV2i-LxlNgpMV7AYVfiE012AtTEGGX9Gk',
    appId: '1:519206703183:ios:cead91fe11ddace9b51a3a',
    messagingSenderId: '519206703183',
    projectId: 'portifolio-d00ca',
    storageBucket: 'portifolio-d00ca.appspot.com',
    iosBundleId: 'com.example.portifolio.RunnerTests',
  );
}
